sudo: required
services:
  - docker

before_install:
  - docker build -t xia0m/fib-test -f ./client/Dockerfile.dev ./client

script:
  - docker run xia0m/fib-test npm test -- --coverage

after_success:
  - docker build -t xia0m/fib-client ./client
  - docker build -t xia0m/fib-nginx ./nginx
  - docker build -t xia0m/fib-server ./server
  - docker build -t xia0m/fib-worker ./worker
  # login to dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push images to docker hub
  - docker push xia0m/fib-client 
  - docker push xia0m/fib-nginx 
  - docker push xia0m/fib-server 
  - docker push xia0m/fib-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: fib-docker
  env:  FibDocker-env
  bucket_name: elasticbeanstalk-us-east-2-562693985953
  bucket_path: fib-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

